services:
  nmr-parse:
    image: nmr-parse
    volumes:
      - ./src:/nmr-parse/src
    ports:
      - 12345:12345
    command: ["python", "-u", "app.py"]
    networks:
      - nmr-parse
      - caddy
networks:
  nmr-parse:
  caddy:
    name: caddy_network
    external: true